### ISSUE TITLE
Should `<ip_address>:<port_number>` be considered as valid?

### ISSUE THREAD

**Issue by nikitaeverywhere** [miguelmota/is-valid-host#1]
Hello! First issue here 🎉

As soon as this package name is `is-valid-host` (but not `-hostname`), I assumed this host will be valid:

- `isValidHost('127.0.0.1:3000') // false` (but it's not, according to [this doc](https://www.npmjs.com/package/is-valid-host))

An example of the "Host" header Chrome sends in the network tab (when you visit `192.168.1.100:32100` in my case):

![image](https://user-images.githubusercontent.com/4989256/91289006-5ed1a980-e79a-11ea-9d3e-e14c89bfdb75.png)

I think the port number should be (optionally) included, or you need to clarify in readme what exactly the `host` stands for. What do you think?

Thank you!

**Comment by miguelmota** [comment]
Hi @ZitRos, thanks for the report! The latest version now allows the port. 

Closed by https://github.com/miguelmota/is-valid-host/commit/910a65b2df16eb9577d1f4f598792f9578b2db34
